---
output: html_document
---
Assignment 1
==================================
##Fernando Colugnati




```{r load data}
#Read the file
a<-read.csv("activity.csv")

#Install packages
#install.packages("plyr")
#install.packages("Hmisc")
#install.packages("doBy")

```


```{r summarize data, warning=FALSE, message=FALSE}
#summarizes dataset and shows statistics for daily steps
summary(a)
desc <- summary(tapply(a$steps, a$date, sum))
ldesc <- summary(tapply(log(a$steps+1), a$date, sum))
desc
ldesc
```

```{r ploting steps by interval}

par(mfrow = c(1, 2))
hist(tapply(a$steps, a$date, sum), main="Daily steps distribution", xlab="Total daily steps")
hist(tapply(log(a$steps+1), a$date, sum), main=" ", xlab="Log(total steps + 1)")

c <- aggregate(steps ~ interval, data=a, FUN=mean)
attach(c)
par(mfrow = c(1, 1))
plot(c, type="l")

c <- c[order(-steps),]
```

The maximun average number of steps is `r round(c[1,2])` at interval `r c[1,1]`

```{r input missings, warning=FALSE, message=FALSE}
require(plyr)
require(Hmisc)

a <- ddply(a, "interval", mutate, steps.mean = impute(steps, mean))
a <- ddply(a, "interval", mutate, steps.median = impute(steps, median))

require(xtable)
xt <- summary(a)
print(xt, type = "html")
```


```{r create weekday factor}
Sys.setlocale("LC_TIME", "C") #I am in Brazil, must do this!

a$weekday <- weekdays(as.Date(a$date), abbreviate=TRUE)

a$weekday_f[a$weekday=="Sat" | a$weekday=="Sun"]<-0
a$weekday_f[a$weekday=="Mon" | a$weekday=="Tue" | a$weekday=="Wed" | 
            a$weekday=="Fri" | a$weekday=="Thu"]<-1
a$weekday_f <- factor(a$weekday_f, levels=c(0,1), labels=c("Weekends", "Weekdays"))

table(a$weekday)
table(a$weekday_f)
```


```{r}
a_weekend <- subset(a, weekday_f=="Weekends")
a_weekday <- subset(a, weekday_f=="Weekdays")

par(mfrow = c(2, 1))
plot(aggregate(steps.mean ~ interval, data=a_weekend, FUN=mean), type="l", sub="Weekend")
plot(aggregate(steps.mean ~ interval, data=a_weekday, FUN=mean), type="l", sub="weekday")

par(mfrow = c(1, 2))
boxplot(a$steps.mean ~ a$weekday,data=a, main="Steps Distribution" , ylab="Number of steps")
boxplot(log(steps.mean+1) ~ weekday,data=a , ylab="Log(Number of steps +1)")

par(mfrow = c(1, 2))
boxplot(a$steps~a$weekday_f,data=a, main="Steps Distribution" , ylab="Number of steps")
boxplot(log(steps+1)~weekday_f,data=a, ylab="Log(Number of steps +1)")

```

```{r}
library(doBy)
summaryBy(steps.mean + steps.median ~ weekday_f, data = a, 
          FUN = function(x) { c(m = mean(x), s = sd(x), md = median(x)) } )

wilcox.test(a_weekend$steps.mean,a_weekday$steps.mean)
wilcox.test(log(a_weekend$steps.mean+1),log(a_weekday$steps.mean+1))

t.test(a_weekend$steps.mean,a_weekday$steps.mean)
t.test(log(a_weekend$steps.mean+1),log(a_weekday$steps.mean+1))


```

